//! CI artifact report types and helpers for ETH2077.
//!
//! This module defines a compact domain model for CI pipeline artifacts,
//! covering proof outputs, benchmark gate outcomes, coverage reports, and
//! reproducibility attestations.
//!
//! The design goals are:
//! - Keep the wire format stable through explicit enum types.
//! - Keep validation conservative and explicit, returning all discovered errors.
//! - Keep aggregate statistics deterministic and easy to inspect.
//! - Keep commitment generation stable across map ordering differences.
//!
//! Notes on interpretation:
//! - `coverage_threshold_pct` and computed `coverage_pct` are percentages in
//!   the range `0.0..=100.0`.
//! - `flaky_rate` is a ratio in the range `0.0..=1.0`.
//! - Gate outcomes are inferred from artifact metadata, using the
//!   `gate_status` key when present.
//! - Coverage values are inferred from artifact metadata, using the
//!   `coverage_pct` key for artifacts of kind `CoverageMap`.
//! - Missing metadata keys only affect derived statistics.
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::HashMap;

/// Describes the concrete type of CI artifact produced by a pipeline run.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ArtifactKind {
    /// Formal proof report generated by theorem proving or proof-check jobs.
    ProofReport,
    /// Benchmark gate output that captures pass/fail/flaky signal for a gate.
    BenchmarkGate,
    /// Coverage report artifact (line, branch, or property coverage maps).
    CoverageMap,
    /// Build reproducibility attestation signed by CI provenance infrastructure.
    BuildAttestation,
    /// Regression diff generated against a baseline release or benchmark suite.
    RegressionDiff,
    /// Fuzzing corpus snapshot or minimized reproducer bundle.
    FuzzCorpus,
}

/// Status used by CI gates represented in artifact metadata.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum GateStatus {
    /// The gate reached the expected success criteria.
    Passed,
    /// The gate reached a clear failure condition.
    Failed,
    /// The gate produced unstable outcomes across retries or environments.
    Flaky,
    /// The gate was intentionally not executed.
    Skipped,
    /// The gate did not complete before its execution budget expired.
    TimedOut,
    /// The gate was overridden by human approval despite non-passing outcomes.
    ManualOverride,
}

/// Serialization or artifact container format.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ReportFormat {
    /// JavaScript Object Notation.
    Json,
    /// HyperText Markup Language.
    Html,
    /// Markdown document.
    Markdown,
    /// Comma-Separated Values file.
    Csv,
    /// Opaque binary payload.
    Binary,
    /// Protocol Buffers encoded payload.
    Protobuf,
}

/// Lifecycle policy that controls retention and cleanup behavior for artifacts.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum RetentionPolicy {
    /// Keep only for immediate inspection in active runs.
    Ephemeral,
    /// Keep for short-lived debugging and release verification windows.
    ShortTerm,
    /// Keep for medium-term trend analysis and postmortem investigations.
    LongTerm,
    /// Keep indefinitely for governance, audit, or legal requirements.
    Permanent,
    /// Archive after a grace period before hard deletion.
    ArchiveAfter,
    /// Purge automatically when all required gates are green.
    PurgeOnPass,
}

/// A single persisted CI artifact.
/// This record is intentionally minimal:
/// - it includes identity (`id`), provenance (`pipeline_run`, `git_sha`),
/// - shape (`kind`, `format`, `size_bytes`), and
/// - retention and arbitrary metadata for extension fields.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CiArtifact {
    /// Stable artifact identifier unique within the CI storage domain.
    pub id: String,
    /// Domain classification of the artifact payload.
    pub kind: ArtifactKind,
    /// CI run identifier (workflow ID, build number, etc.).
    pub pipeline_run: String,
    /// Source revision digest (typically a full commit SHA).
    pub git_sha: String,
    /// Artifact encoding or representation format.
    pub format: ReportFormat,
    /// Artifact size in bytes as stored by the pipeline backend.
    pub size_bytes: u64,
    /// Retention policy applied by storage and lifecycle automation.
    pub retention: RetentionPolicy,
    /// Arbitrary key/value metadata for status, dimensions, and provenance tags.
    pub metadata: HashMap<String, String>,
}

/// Configuration for CI artifact management, gate expectations, and quality bars.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CiArtifactsConfig {
    /// Maximum allowed artifact size in megabytes.
    pub max_artifact_size_mb: u64,
    /// Default artifact retention duration in whole days.
    pub retention_days: u64,
    /// Names of required CI gates that must be represented by artifacts.
    pub required_gates: Vec<String>,
    /// Whether reproducibility attestations are mandatory in the pipeline.
    pub reproducibility_check: bool,
    /// Minimum accepted coverage percentage.
    pub coverage_threshold_pct: f64,
    /// Number of fuzz iterations expected before artifact publication.
    pub fuzz_iterations: u64,
    /// Arbitrary metadata to scope policy variants (team, branch class, etc.).
    pub metadata: HashMap<String, String>,
}

/// Validation error for [`CiArtifactsConfig`].
/// Errors are reported as field/reason pairs to keep downstream rendering simple
/// in CLI tools, APIs, and CI dashboards.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CiArtifactsValidationError {
    /// Name of the field that failed validation.
    pub field: String,
    /// Human-readable reason describing the invalid condition.
    pub reason: String,
}

/// Aggregate statistics computed from a list of CI artifacts.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CiArtifactsStats {
    /// Number of artifacts included in the analysis window.
    pub total_artifacts: usize,
    /// Number of parsed gate results counted as passed.
    pub passed_gates: usize,
    /// Number of parsed gate results counted as failed.
    pub failed_gates: usize,
    /// Fraction of parsed gates marked flaky (`0.0..=1.0`).
    pub flaky_rate: f64,
    /// Mean artifact size in bytes.
    pub avg_size_bytes: f64,
    /// Mean coverage percentage from coverage artifacts (`0.0..=100.0`).
    pub coverage_pct: f64,
}

/// Returns a conservative default configuration for ETH2077 CI artifact handling.
///
/// Defaults emphasize:
/// - practical artifact size limits,
/// - non-zero retention,
/// - explicit gate requirements,
/// - reproducibility by default,
/// - and a meaningful baseline coverage threshold.
pub fn default_ci_artifacts_config() -> CiArtifactsConfig {
    let mut metadata = HashMap::new();
    metadata.insert("profile".to_string(), "eth2077-default".to_string());
    metadata.insert("provenance".to_string(), "ci-v1".to_string());

    CiArtifactsConfig {
        max_artifact_size_mb: 512,
        retention_days: 30,
        required_gates: vec![
            "proof".to_string(),
            "benchmark".to_string(),
            "coverage".to_string(),
            "reproducibility".to_string(),
        ],
        reproducibility_check: true,
        coverage_threshold_pct: 85.0,
        fuzz_iterations: 100_000,
        metadata,
    }
}

/// Validates a CI artifact configuration and returns all discovered errors.
///
/// Validation rules:
/// - `max_artifact_size_mb` must be non-zero.
/// - `retention_days` must be non-zero.
/// - `required_gates` must contain at least one non-empty gate name.
/// - `required_gates` entries must be unique after trimming.
/// - `coverage_threshold_pct` must be finite and inside `0.0..=100.0`.
/// - `fuzz_iterations` must be non-zero.
/// - metadata keys must be non-empty.
///
/// The function intentionally does not enforce project-specific naming schemes,
/// so teams can evolve their gate taxonomy independently.
pub fn validate_ci_artifacts_config(
    config: &CiArtifactsConfig,
) -> Result<(), Vec<CiArtifactsValidationError>> {
    let mut errors = Vec::new();

    if config.max_artifact_size_mb == 0 {
        errors.push(CiArtifactsValidationError {
            field: "max_artifact_size_mb".to_string(),
            reason: "must be greater than zero".to_string(),
        });
    }

    if config.retention_days == 0 {
        errors.push(CiArtifactsValidationError {
            field: "retention_days".to_string(),
            reason: "must be greater than zero".to_string(),
        });
    }

    if config.required_gates.is_empty() {
        errors.push(CiArtifactsValidationError {
            field: "required_gates".to_string(),
            reason: "must include at least one gate".to_string(),
        });
    }

    let mut seen_gates: HashMap<String, usize> = HashMap::new();
    for gate in &config.required_gates {
        let normalized = gate.trim();
        if normalized.is_empty() {
            errors.push(CiArtifactsValidationError {
                field: "required_gates".to_string(),
                reason: "gate names must not be empty or whitespace".to_string(),
            });
            continue;
        }

        let count = seen_gates.entry(normalized.to_string()).or_insert(0);
        *count += 1;
        if *count > 1 {
            errors.push(CiArtifactsValidationError {
                field: "required_gates".to_string(),
                reason: format!("duplicate gate name '{normalized}'"),
            });
        }
    }

    if !(config.coverage_threshold_pct.is_finite()
        && (0.0..=100.0).contains(&config.coverage_threshold_pct))
    {
        errors.push(CiArtifactsValidationError {
            field: "coverage_threshold_pct".to_string(),
            reason: "must be finite and in range 0..=100".to_string(),
        });
    }

    if config.fuzz_iterations == 0 {
        errors.push(CiArtifactsValidationError {
            field: "fuzz_iterations".to_string(),
            reason: "must be greater than zero".to_string(),
        });
    }

    for key in config.metadata.keys() {
        if key.trim().is_empty() {
            errors.push(CiArtifactsValidationError {
                field: "metadata".to_string(),
                reason: "metadata keys must not be empty".to_string(),
            });
        }
    }

    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors)
    }
}

/// Computes aggregate metrics from artifact records.
///
/// Gate counting uses `metadata["gate_status"]` when present.
/// Recognized status values are case-insensitive enum names, for example:
/// - `passed`
/// - `failed`
/// - `flaky`
/// - `skipped`
/// - `timedout`
/// - `manualoverride`
///
/// Coverage averaging uses only artifacts with `kind == ArtifactKind::CoverageMap`
/// and a parseable `metadata["coverage_pct"]` value in the inclusive range
/// `0.0..=100.0`.
pub fn compute_ci_artifacts_stats(artifacts: &[CiArtifact]) -> CiArtifactsStats {
    let total_artifacts = artifacts.len();

    let mut total_size_bytes = 0.0_f64;
    let mut passed_gates = 0_usize;
    let mut failed_gates = 0_usize;
    let mut flaky_gates = 0_usize;
    let mut observed_gates = 0_usize;

    let mut coverage_sum = 0.0_f64;
    let mut coverage_count = 0_usize;

    for artifact in artifacts {
        total_size_bytes += artifact.size_bytes as f64;

        if let Some(status) = gate_status_from_metadata(&artifact.metadata) {
            observed_gates += 1;
            match status {
                GateStatus::Passed | GateStatus::ManualOverride => {
                    passed_gates += 1;
                }
                GateStatus::Failed | GateStatus::TimedOut => {
                    failed_gates += 1;
                }
                GateStatus::Flaky => {
                    flaky_gates += 1;
                }
                GateStatus::Skipped => {}
            }
        }

        if artifact.kind == ArtifactKind::CoverageMap {
            if let Some(value) = coverage_from_metadata(&artifact.metadata) {
                coverage_sum += value;
                coverage_count += 1;
            }
        }
    }

    let flaky_rate = if observed_gates == 0 {
        0.0
    } else {
        flaky_gates as f64 / observed_gates as f64
    };

    let avg_size_bytes = if total_artifacts == 0 {
        0.0
    } else {
        total_size_bytes / total_artifacts as f64
    };

    let coverage_pct = if coverage_count == 0 {
        0.0
    } else {
        coverage_sum / coverage_count as f64
    };

    CiArtifactsStats {
        total_artifacts,
        passed_gates,
        failed_gates,
        flaky_rate,
        avg_size_bytes,
        coverage_pct,
    }
}

/// Computes a deterministic SHA-256 commitment for the configuration.
///
/// The output is a lowercase hexadecimal string.
///
/// Canonicalization rules:
/// - scalar fields are encoded with explicit keys,
/// - `required_gates` are sorted lexicographically before encoding,
/// - metadata entries are sorted by key, then value,
/// - values are length-prefixed to avoid delimiter ambiguity.
pub fn compute_ci_artifacts_commitment(config: &CiArtifactsConfig) -> String {
    let mut hasher = Sha256::new();
    hasher.update(b"ETH2077::CI_ARTIFACTS::CONFIG::V1");

    append_kv(
        &mut hasher,
        "max_artifact_size_mb",
        &config.max_artifact_size_mb.to_string(),
    );
    append_kv(
        &mut hasher,
        "retention_days",
        &config.retention_days.to_string(),
    );
    append_kv(
        &mut hasher,
        "reproducibility_check",
        if config.reproducibility_check {
            "true"
        } else {
            "false"
        },
    );
    append_kv(
        &mut hasher,
        "coverage_threshold_pct",
        &normalize_float(config.coverage_threshold_pct),
    );
    append_kv(
        &mut hasher,
        "fuzz_iterations",
        &config.fuzz_iterations.to_string(),
    );

    append_sorted_string_vec(&mut hasher, "required_gates", &config.required_gates);
    append_sorted_metadata(&mut hasher, "metadata", &config.metadata);

    let digest = hasher.finalize();
    digest_to_hex(&digest)
}

fn gate_status_from_metadata(metadata: &HashMap<String, String>) -> Option<GateStatus> {
    metadata
        .get("gate_status")
        .and_then(|value| parse_gate_status(value))
}

fn parse_gate_status(raw: &str) -> Option<GateStatus> {
    let normalized = raw.trim().to_ascii_lowercase().replace([' ', '-', '_'], "");

    match normalized.as_str() {
        "passed" => Some(GateStatus::Passed),
        "failed" => Some(GateStatus::Failed),
        "flaky" => Some(GateStatus::Flaky),
        "skipped" => Some(GateStatus::Skipped),
        "timedout" => Some(GateStatus::TimedOut),
        "manualoverride" => Some(GateStatus::ManualOverride),
        _ => None,
    }
}

fn coverage_from_metadata(metadata: &HashMap<String, String>) -> Option<f64> {
    let raw = metadata.get("coverage_pct")?;
    let parsed = raw.parse::<f64>().ok()?;
    if parsed.is_finite() && (0.0..=100.0).contains(&parsed) {
        Some(parsed)
    } else {
        None
    }
}

fn append_kv(hasher: &mut Sha256, key: &str, value: &str) {
    hasher.update(format!("{key}:{}:{value};", value.len()).as_bytes());
}

fn append_sorted_string_vec(hasher: &mut Sha256, key: &str, values: &[String]) {
    let mut sorted = values.to_vec();
    sorted.sort();
    append_kv(hasher, &format!("{key}.len"), &sorted.len().to_string());
    for value in sorted {
        append_kv(hasher, key, &value);
    }
}

fn append_sorted_metadata(hasher: &mut Sha256, key: &str, metadata: &HashMap<String, String>) {
    let mut entries: Vec<(&String, &String)> = metadata.iter().collect();
    entries.sort_by(|(key_a, value_a), (key_b, value_b)| {
        if key_a == key_b {
            value_a.cmp(value_b)
        } else {
            key_a.cmp(key_b)
        }
    });

    append_kv(hasher, &format!("{key}.len"), &entries.len().to_string());
    for (entry_key, entry_value) in entries {
        append_kv(
            hasher,
            &format!("{key}.{}", entry_key.trim()),
            entry_value.trim(),
        );
    }
}

fn normalize_float(value: f64) -> String {
    if !value.is_finite() {
        return "NaN".to_string();
    }

    // Fixed precision keeps commitment output stable across equivalent encoders.
    format!("{value:.6}")
}

fn digest_to_hex(digest: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(digest.len() * 2);

    for byte in digest {
        out.push(HEX[(byte >> 4) as usize] as char);
        out.push(HEX[(byte & 0x0f) as usize] as char);
    }

    out
}
